fix: KeyError in check_bills_all_vehicles due to missing 'number_plat…
aakvatech/CSF_TZ pull request #328
Opened 2024-05-31 13:55 UTC by nelsonmpanju

…e' key

2024-06-04 04:44 UTC, aakvatech requested changes
Log error should have title and message parameter names

2024-06-19 11:54 UTC, miteshpc approved these changes

2024-06-19 11:55 UTC, miteshpc approved these changes

2024-06-19 11:56 UTC, aakvatech approved these changes

2024-06-19 11:56 UTC, merged